# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :custom_lane do
    # add actions here: https://docs.fastlane.tools/actions
  end

  lane :to_firim do
    sigh(adhoc: true)

    increment_build_number_in_plist(target: [target_name])
    increment_version_number_in_plist(
      targete: [target_name],
      version_number: '7.1.3'
    )

    gym(
      output_directory: './firim',
      export_options: {
        method: "ad-hoc",
        thinning: "<none>"
      }
      )
    # firim(firim_api_token: [firim_api_token])
  end

  lane :deploy do
    sigh
    increment_build_number_in_plist(target: [target_name])
    increment_version_number_in_plist(
      target: [target_name],
      version_number: '7.1.3'
    )

    gym(
      output_directory: './build',
      )
    deliver(force:true)
  end

end
